INSERT INTO project_worker (project_id, worker_id)
VALUES
    (1, 2), -- 'Spider-Man: Homecoming', 'Peter Parker'
    (1, 3), -- 'Spider-Man: Homecoming', 'Tony Stark'
    (2, 1), -- 'Guardians of the Galaxy', 'Peter Quill'
    (2, 7), -- 'Guardians of the Galaxy', 'Groot'
    (3, 2), -- 'Captain America: Civil War', 'Peter Parker'
    (3, 3), -- 'Captain America: Civil War', 'Tony Stark'
    (3, 4), -- 'Captain America: Civil War', 'Clint Barton'
    (3, 6), -- 'Captain America: Civil War', 'Steven Rogers'
    (3, 8), -- 'Captain America: Civil War', 'Natalia Romanova'
    (4, 3), -- 'Iron Man', 'Tony Stark'
    (4, 9), -- 'Iron Man', 'Pepper Pots'
    (5, 3), -- 'The Avengers', 'Tony Stark'
    (5, 4), -- 'The Avengers', 'Clint Barton'
    (5, 6), -- 'The Avengers', 'Steven Rogers'
    (5, 8), -- 'The Avengers', 'Natalia Romanova'
    (5, 10), -- 'The Avengers', 'Thor Odinson'
    (6, 3), -- 'Avengers: Endgame', 'Tony Stark'
    (6, 4), -- 'Avengers: Endgame', 'Clint Barton'
    (6, 6), -- 'Avengers: Endgame', 'Steven Rogers'
    (6, 9), -- 'Avengers: Endgame', Pepper Pots'
    (6, 10), -- 'Avengers: Endgame', 'Thor Odinson'
    (7, 2), -- 'Avengers: Infinity War', 'Peter Parker'
    (7, 3), -- 'Avengers: Infinity War', 'Tony Stark'
    (7, 6), -- 'Avengers: Infinity War', 'Steven Rogers'
    (7, 10), -- 'Avengers: Infinity War', 'Thor Odinson'
    (8, 3), -- 'Avengers: Age of Ultron', 'Tony Stark'
    (8, 4), -- 'Avengers: Age of Ultron', 'Clint Barton'
    (8, 6), -- 'Avengers: Age of Ultron', 'Steven Rogers'
    (8, 8), -- 'Avengers: Age of Ultron', 'Natalia Romanova'
    (9, 1), -- 'Guardians of the Galaxy Vol. 3', 'Peter Quill'
    (9, 7), -- 'Guardians of the Galaxy Vol. 3', 'Groot'
    (10, 6), -- 'Avengers: Age of Ultron', 'Steven Rogers'
    (10, 8); -- 'Avengers: Age of Ultron', 'Natalia Romanova'